fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "no-reply@yunkun.org"
        sender_name: "UMS TEST"
    use_listener: false
    registration:
        form:
            type: App\Form\RegistrationType
    profile:
        form:
            type: App\Form\ProfileType
    service:
        mailer: fos_user.mailer.default
        email_canonicalizer:  fos_user.util.canonicalizer.default
        token_generator:      fos_user.util.token_generator.default
