#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /
    defaults:
        _controller: App\Controller\IndexController::index

userpage:
    path: /user
    defaults:
        _controller: App\Controller\UserController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

registration_confirm:
    path: /registration/user_confirm/{token}
    defaults:
        _controller: App\Controller\UserController::registration_confirm

purchasehistory:
    path: /purchase/history
    defaults:
        _controller: App\Controller\PurchaseController::index